services:
  flask:
    restart: unless-stopped
    image: python:3.11-slim
    volumes:
      - ../../../app:/app
    working_dir: /app
    command: sh -lc "pip install --no-cache-dir flask==3.1.2 && python app.py"

  nginx:
    restart: unless-stopped
    image: nginx:stable
    ports:
      - "8443:8443"
    environment:
      - DOCKER_UID=${DOCKER_UID}
      - DOCKER_GID=${DOCKER_GID}
    command: >
      sh -lc "
        chown -R ${DOCKER_UID}:${DOCKER_GID} /var/log/nginx 2>/dev/null || true;
        exec nginx -g 'daemon off;'
      "
    volumes:
      - ./case-nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../../certs:/etc/nginx/certs:ro
      - ../../../runlogs/nginx:/var/log/nginx
    depends_on:
      - flask