"""
Classifies a single run failure into a Trust Decision Graph (TDG) outcome.
It currently supports the following failure archetypes:
  - MissingPeerCredentialsFailure (server verifies client)
  - TrustAnchorResolutionFailure (client verifies self-signed server, wrong anchor x2 directions)
  - IncompleteChainFailure (client verifies server, server verifies client)
  - PrivateKeyProofFailure (server verifiers client)
  - ValidityWindowFailure (expired/not-yet-valid x2 directions)
  - UsageConstraintFailure (EKU/BasicConstraints server verifies client)
  - SubjectIdentityMismatchFailure (client verifies server)

Supports soft-fail detection: verification failures that still result in request
acceptance are flagged with warning=True and status=ACCEPT.

Uses evidence files generated by:
  - run.sh
  - collect-evidence.sh

Does not use:
  - metadata/run_case.txt (input about the failure intended to be replayed)

Analysis results are written alongside the evidence files in:
  - result.json
  - result.txt
"""
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Dict, Any, List, Tuple

from failures_classifier import FAILURES_CLASSIFIER


# ===== SUPPORT FUNCTIONS =====
def read_text(out_dir: Path, relative_path: str) -> str:
    """
    Read a text file under OUT_DIR.
    Returns empty string if the file does not exist or cannot be read.
    """
    try:
        return (out_dir / relative_path).read_text(errors="replace")
    except Exception:
        return ""


def first_regex_match(text: str, patterns: List[str]) -> Optional[str]:
    """
    Return the first matching substring for any regex in patterns, else None.
    """
    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE | re.MULTILINE)
        if match:
            return match.group(0).strip()
    return None


def get_case_metadata(archetype: str, case: str) -> Dict[str, Any]:
    """
    Retrieve metadata for a specific case from the failures classifier.
    """
    archetype_entry = FAILURES_CLASSIFIER.get(archetype, {})
    for case_obj in archetype_entry.get("cases", []):
        if case in case_obj:
            return case_obj[case]
    return {}


def check_exclusions(text: str, exclusions: List[str]) -> bool:
    """
    Check if any exclusion patterns match in the text.
    Returns True if any exclusion is found (meaning this case should be excluded).
    """
    if not exclusions:
        return False
    for pattern in exclusions:
        if re.search(pattern, text, flags=re.IGNORECASE):
            return True
    return False


def parse_utc_time_text(text: str) -> Optional[datetime]:
    """
    Parse a UTC time from text.
    Supported format examples:
      - ISO: 2026-02-28T12:34:56Z
      - date -u: Sat Feb 28 12:34:56 UTC 2026
    """
    if not text:
        return None
    iso_match = re.search(r"(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})Z", text)
    if iso_match:
        try:
            return datetime.fromisoformat(iso_match.group(1)).replace(tzinfo=timezone.utc)
        except Exception:
            return None
    compact = re.sub(r"\s+", " ", text.strip())
    try:
        return datetime.strptime(compact, "%a %b %d %H:%M:%S UTC %Y").replace(tzinfo=timezone.utc)
    except Exception:
        return None


def verify_time_utc(out_dir: Path) -> Optional[datetime]:
    """
    Return the verification time in UTC.
    This is only used as a fallback for ValidityWindowFailure when logs do not
    contain explicit "expired/not yet valid" strings.
    """
    nginx_time_text = read_text(out_dir, "server/nginx_time_utc.txt").strip()
    host_time_text = read_text(out_dir, "environment/host_time_utc.txt").strip()
    return parse_utc_time_text(nginx_time_text) or parse_utc_time_text(host_time_text)


def parse_notbefore_notafter(cert_fields_text: str) -> Tuple[Optional[datetime], Optional[datetime]]:
    """
    Parse notBefore / notAfter from a certs/fields/*.txt file.
    """
    if not cert_fields_text:
        return None, None
    nb_match = re.search(r"notBefore\s*=\s*(.+)", cert_fields_text)
    na_match = re.search(r"notAfter\s*=\s*(.+)", cert_fields_text)
    def parse_gmt(value: str) -> Optional[datetime]:
        value = value.strip()
        try:
            return datetime.strptime(value, "%b %d %H:%M:%S %Y GMT").replace(tzinfo=timezone.utc)
        except Exception:
            return None
    not_before = parse_gmt(nb_match.group(1)) if nb_match else None
    not_after = parse_gmt(na_match.group(1)) if na_match else None
    return not_before, not_after


def count_certificates(text: str) -> int:
    """
    Count the number of certificates in a file/text.
    Works for leaf-only, fullchain, or bundles.
    """
    if not text:
        return 0
    return len(re.findall(r"-----BEGIN CERTIFICATE-----", text))


def extract_pubkey_hash(hash_file_text: str) -> str:
    """
    Extract the SHA-256 hash from a pubkey_sha256.txt file.

    The hash is always on the last non-empty line, first whitespace-delimited token.
    Strips surrounding whitespace and newlines before splitting to guard against
    files with trailing blank lines.
    """
    lines = [line.strip() for line in hash_file_text.splitlines() if line.strip()]
    if not lines:
        return ""
    return lines[-1].split()[0]

# ===== RESULT BUILDERS =====
def build_failure_result(
    archetype: str,
    case: str,
    evidence_file: str,
    failure_signal: str,
    verifier: str,
    is_deterministic: bool,
) -> Dict[str, Any]:
    """
    Map result to classifier by building a standard output payload for a detected failure case.
    Inputs:
      - archetype: key in FAILURES_CLASSIFIER
      - case: case name under archetype["cases"]
      - evidence_file: human-readable evidence location (no paths, just the file used)
      - failure_signal: concrete snippet that triggered detection
      - verifier: which verifier detected this failure ("client" or "server")
      - is_deterministic: whether the failure is deterministic (always triggers) or not (relies on logs that may not invoke the failure)

    Status and warning are set by the analyzer orchestration based on whether the request
    was accepted despite the verification failure (soft-fail).
    """
    archetype_entry = FAILURES_CLASSIFIER[archetype]
    selected_case_entry = next((case_obj[case] for case_obj in archetype_entry["cases"] if case in case_obj), {})

    # Validate verifier is supported by this case
    detected_by_list = selected_case_entry.get("detected_by", [])
    if verifier not in detected_by_list:
        raise ValueError(f"Verifier '{verifier}' not in detected_by list {detected_by_list} for {archetype}/{case}")


    return {
        "status": "REJECT",
        "warning": False,
        "archetype": archetype,
        "case": case,
        "detected_by": verifier,
        "is_deterministic": is_deterministic,
        "decision_step": {
            "step_id": archetype_entry["step_id"],
            "step_name": archetype_entry["step_name"],
            "decision": archetype_entry["decision"],
        },
        "failing_input": selected_case_entry.get("failing_input", ""),
        "evidence_file": evidence_file,
        "failure_signal": failure_signal,
        "symptom": selected_case_entry.get("symptom", ""),
        "minimal_fix": selected_case_entry.get("minimal_fix", ""),
    }


def build_success_result(evidence_file: str, success_signal: str) -> Dict[str, Any]:
    """
    Build the baseline output payload for success.
    """
    return {
        "status": "ACCEPT",
        "warning": False,
        "archetype": "",
        "case": "BaselineSuccess",
        "detected_by": "both",
        "decision_step": None,
        "failing_input": "",
        "evidence_file": evidence_file,
        "failure_signal": success_signal,
        "symptom": "Handshake and request succeeded.",
        "minimal_fix": "None.",
    }


def build_unknown_result(out_dir: Path) -> Dict[str, Any]:
    """
    Return UnknownOutcome for unclassified results
    Possible causes:
      - Case not yet implemented in the analyzer.
      - Not enough evidence.
      - Pattern detection needs updating.
    """
    handshake = read_text(out_dir, "client/handshake.txt")
    error_log = read_text(out_dir, "server/error.log")

    best_signal = (
        first_regex_match(handshake, (
            r"SSL certificate problem:.*",
            r"certificate verify failed.*",
            r"no alternative certificate subject name matches.*",
            r"no peer certificate available.*",
            r"self signed certificate.*",
        ))
        or first_regex_match(error_log, (
            r"SSL_do_handshake\(\) failed.*",
            r"certificate verify failed.*",
            r".*failed.*",
        ))
        or "No strong signal found in collected evidence."
    )

    return {
        "status": "REJECT",
        "warning": False,
        "archetype": "",
        "case": "UnknownOutcome",
        "detected_by": "unknown",
        "decision_step": None,
        "failing_input": "",
        "evidence_file": "client/handshake.txt or server/error.log",
        "failure_signal": best_signal,
        "symptom": "Analyzer could not map this run to an implemented case using collected evidence.",
        "minimal_fix": "Inspect client/handshake.txt and server/error.log; confirm collect-evidence used the correct COMPOSE_DIR.",
    }


# ===== FAILURE DETECTION =====
def detect_missing_client_certificate_case(out_dir: Path) -> Optional[Dict[str, Any]]:
    """
    Detects: MissingPeerCredentialsFailure > MissingClientCertificateCase
    Direction: server verifies client
    Deterministic: No (log-based)
    Evidence: server/error.log
    """
    archetype = "MissingPeerCredentialsFailure"
    case = "MissingClientCertificateCase"
    metadata = get_case_metadata(archetype, case)

    error_log = read_text(out_dir, metadata["evidence_file"])
    signal = first_regex_match(error_log, metadata["signals"])
    if not signal:
        return None

    return build_failure_result(
        archetype,
        case,
        evidence_file=metadata["evidence_file"],
        failure_signal=signal,
        verifier="server",
        is_deterministic=False,
    )


def detect_certificateverify_signature_mismatch_case(out_dir: Path) -> Optional[Dict[str, Any]]:
    """
    Detects: PrivateKeyProofFailure > CertificateVerifySignatureMismatchCase
    Direction: server verifies client
    Deterministic: Yes (hash comparison)
    Evidence: inputs/client/key.pubkey_sha256.txt + inputs/client/cert.pubkey_sha256.txt
    """
    archetype = "PrivateKeyProofFailure"
    case = "CertificateVerifySignatureMismatchCase"
    metadata = get_case_metadata(archetype, case)

    key_hash_text = read_text(out_dir, "inputs/client/key.pubkey_sha256.txt").strip()
    cert_hash_text = read_text(out_dir, "inputs/client/cert.pubkey_sha256.txt").strip()

    key_hash = extract_pubkey_hash(key_hash_text)
    cert_hash = extract_pubkey_hash(cert_hash_text)

    if not key_hash or not cert_hash:
        return None
    if key_hash == cert_hash:
        return None

    signal = f"pubkey_sha256 mismatch (key={key_hash} cert={cert_hash})"
    return build_failure_result(
        archetype,
        case,
        evidence_file=metadata["evidence_file"],
        failure_signal=signal,
        verifier="server",
        is_deterministic=True,
    )


def detect_missing_intermediate_server_cert_case(out_dir: Path) -> Optional[Dict[str, Any]]:
    """
    Detects: IncompleteChainFailure > MissingIntermediateCase
    Direction: client verifies server
    Deterministic: No (log-based + cert count check)
    Evidence: client/handshake.txt
    """
    archetype = "IncompleteChainFailure"
    case = "MissingIntermediateCase"
    metadata = get_case_metadata(archetype, case)

    handshake = read_text(out_dir, "client/handshake.txt")

    # Check exclusions
    if check_exclusions(handshake, metadata["exclusions"]):
        return None

    issuer_signal = first_regex_match(handshake, metadata["signals"])
    if not issuer_signal:
        return None

    presented_cert_text = read_text(out_dir, "inputs/server/fullchain.crt")
    presented_count = count_certificates(presented_cert_text)
    if presented_count != 1:
        return None
    signal = f"{issuer_signal} (presented_certs={presented_count})"

    return build_failure_result(
        archetype,
        case,
        evidence_file="client/handshake.txt",
        failure_signal=signal,
        verifier="client",
        is_deterministic=False
    )


def detect_missing_intermediate_client_cert_case(out_dir: Path) -> Optional[Dict[str, Any]]:
    """
    Detects: IncompleteChainFailure > MissingIntermediateCase
    Direction: server verifies client
    Deterministic: No (log-based + cert count check)
    Evidence: server/error.log
    """
    archetype = "IncompleteChainFailure"
    case = "MissingIntermediateCase"
    metadata = get_case_metadata(archetype, case)

    error_log = read_text(out_dir, "server/error.log")
    issuer_signal = first_regex_match(error_log, metadata["signals"])
    if not issuer_signal:
        return None

    presented_cert_text = read_text(out_dir, "inputs/client/cert.crt")
    presented_count = count_certificates(presented_cert_text)
    if presented_count != 1:
        return None
    signal = f"{issuer_signal} (presented_certs={presented_count})"

    return build_failure_result(
        archetype,
        case,
        evidence_file="server/error.log",
        failure_signal=signal,
        verifier="server",
        is_deterministic=False
    )


def detect_untrusted_self_signed_leaf_case(out_dir: Path) -> Optional[Dict[str, Any]]:
    """
    Detects: TrustAnchorResolutionFailure > UntrustedSelfSignedLeafCase
    Direction: client verifies server
    Deterministic: No (log-based)
    Evidence: client/handshake.txt
    """
    archetype = "TrustAnchorResolutionFailure"
    case = "UntrustedSelfSignedLeafCase"
    metadata = get_case_metadata(archetype, case)

    handshake = read_text(out_dir, metadata["evidence_file"])
    signal = first_regex_match(handshake, metadata["signals"])
    if not signal:
        return None

    return build_failure_result(
        archetype,
        case,
        evidence_file=metadata["evidence_file"],
        failure_signal=signal,
        verifier="client",
        is_deterministic=False
    )


def detect_wrong_trust_anchor_server_cert_case(out_dir: Path) -> Optional[Dict[str, Any]]:
    """
    Detects: TrustAnchorResolutionFailure > WrongTrustAnchorCase
    Direction: client verifies server
    Deterministic: No (log-based + cert count check)
    Evidence: client/handshake.txt
    """
    archetype = "TrustAnchorResolutionFailure"
    case = "WrongTrustAnchorCase"
    metadata = get_case_metadata(archetype, case)

    handshake = read_text(out_dir, "client/handshake.txt")

    # Check exclusions
    if check_exclusions(handshake, metadata["exclusions"]):
        return None

    # Check if it's actually missing intermediate (leaf-only)
    # Limitation: partial chains (leaf + some intermediates, but not all) have count > 1
    # and will be misclassified as WrongTrustAnchorCase rather than IncompleteChainFailure.
    presented_cert_text = read_text(out_dir, "inputs/server/fullchain.crt")
    if count_certificates(presented_cert_text) == 1:
        return None

    signal = first_regex_match(handshake, metadata["signals"])
    if not signal:
        return None

    # If it's explicitly the self-signed leaf, that is a different case.
    if re.search(r"self[- ]signed certificate", signal, flags=re.IGNORECASE):
        return None

    return build_failure_result(
        archetype,
        case,
        evidence_file="client/handshake.txt",
        failure_signal=signal,
        verifier="client",
        is_deterministic=False
    )


def detect_wrong_trust_anchor_client_cert_case(out_dir: Path) -> Optional[Dict[str, Any]]:
    """
    Detects: TrustAnchorResolutionFailure > WrongTrustAnchorCase
    Direction: server verifies client
    Deterministic: No (log-based + cert count check)
    Evidence: server/error.log
    """
    archetype = "TrustAnchorResolutionFailure"
    case = "WrongTrustAnchorCase"
    metadata = get_case_metadata(archetype, case)

    error_log = read_text(out_dir, "server/error.log")

    # Check exclusions
    if check_exclusions(error_log, metadata["exclusions"]):
        return None

    # Exclusion: BasicConstraints violation (CA:TRUE on client cert)
    # nginx may log "certificate verify failed" without "unsuitable certificate purpose"
    fields = read_text(out_dir, "certs/fields/client_cert.txt")
    if re.search(r"CA:TRUE", fields, flags=re.IGNORECASE):
        return None

    # Check if it's actually missing intermediate (leaf-only)
    # count == 0 means no client cert was presented;
    # count == 1 means leaf-only;
    # Limitation: partial chains (leaf + some intermediates, but not all) have count > 1
    # and will be misclassified as WrongTrustAnchorCase rather than IncompleteChainFailure.
    presented_cert_text = read_text(out_dir, "inputs/client/cert.crt")
    if count_certificates(presented_cert_text) == 1:
        return None

    signal = first_regex_match(error_log, metadata["signals"])
    if not signal:
        return None

    return build_failure_result(
        archetype,
        case,
        evidence_file="server/error.log",
        failure_signal=signal,
        verifier="server",
        is_deterministic=False
    )


def detect_expired_server_cert_case(out_dir: Path) -> Optional[Dict[str, Any]]:
    """
    Detects: ValidityWindowFailure > ExpiredCertificateCase
    Direction: client verifies server
    Deterministic: No (log-based)
    Evidence: client/handshake.txt
    """
    archetype = "ValidityWindowFailure"
    case = "ExpiredCertificateCase"
    metadata = get_case_metadata(archetype, case)

    handshake = read_text(out_dir, "client/handshake.txt")
    signal = first_regex_match(handshake, metadata["signals"])
    if not signal:
        return None

    return build_failure_result(
        archetype,
        case,
        evidence_file="client/handshake.txt",
        failure_signal=signal,
        verifier="client",
        is_deterministic=False
    )


def detect_expired_client_cert_case(out_dir: Path) -> Optional[Dict[str, Any]]:
    """
    Detects: ValidityWindowFailure > ExpiredCertificateCase
    Direction: server verifies client
    Deterministic: No (log-based with fallback to datetime comparison)
    Evidence: server/error.log OR certs/fields/client_cert.txt + server/nginx_time_utc.txt
    """
    archetype = "ValidityWindowFailure"
    case = "ExpiredCertificateCase"
    metadata = get_case_metadata(archetype, case)

    error_log = read_text(out_dir, "server/error.log")
    signal = first_regex_match(error_log, metadata["signals"])
    if signal:
        return build_failure_result(
            archetype,
            case,
            evidence_file="server/error.log",
            failure_signal=signal,
            verifier="server",
            is_deterministic=False
        )

    # Fallback: datetime comparison
    now_utc = verify_time_utc(out_dir)
    not_before, not_after = parse_notbefore_notafter(read_text(out_dir, "certs/fields/client_cert.txt"))

    if now_utc and not_after and now_utc > not_after:
        signal = f"now={now_utc.isoformat()} > notAfter={not_after.isoformat()}"
        return build_failure_result(
            archetype,
            case,
            evidence_file="certs/fields/client_cert.txt + server/nginx_time_utc.txt",
            failure_signal=signal,
            verifier="server",
        is_deterministic=False
        )

    return None


def detect_not_yet_valid_server_cert_case(out_dir: Path) -> Optional[Dict[str, Any]]:
    """
    Detects: ValidityWindowFailure > NotYetValidCertificateCase
    Direction: client verifies server
    Deterministic: No (log-based)
    Evidence: client/handshake.txt
    """
    archetype = "ValidityWindowFailure"
    case = "NotYetValidCertificateCase"
    metadata = get_case_metadata(archetype, case)

    handshake = read_text(out_dir, "client/handshake.txt")
    signal = first_regex_match(handshake, metadata["signals"])
    if not signal:
        return None

    return build_failure_result(
        archetype,
        case,
        evidence_file="client/handshake.txt",
        failure_signal=signal,
        verifier="client",
        is_deterministic=False
    )


def detect_not_yet_valid_client_cert_case(out_dir: Path) -> Optional[Dict[str, Any]]:
    """
    Detects: ValidityWindowFailure > NotYetValidCertificateCase
    Direction: server verifies client
    Deterministic: No (log-based with fallback to datetime comparison)
    Evidence: server/error.log OR certs/fields/client_cert.txt + server/nginx_time_utc.txt
    """
    archetype = "ValidityWindowFailure"
    case = "NotYetValidCertificateCase"
    metadata = get_case_metadata(archetype, case)

    error_log = read_text(out_dir, "server/error.log")
    signal = first_regex_match(error_log, metadata["signals"])
    if signal:
        return build_failure_result(
            archetype,
            case,
            evidence_file="server/error.log",
            failure_signal=signal,
            verifier="server",
        is_deterministic=False
        )

    # Fallback: datetime comparison
    now_utc = verify_time_utc(out_dir)
    not_before, _not_after = parse_notbefore_notafter(read_text(out_dir, "certs/fields/client_cert.txt"))

    if now_utc and not_before and now_utc < not_before:
        signal = f"now={now_utc.isoformat()} < notBefore={not_before.isoformat()}"
        return build_failure_result(
            archetype,
            case,
            evidence_file="certs/fields/client_cert.txt + server/nginx_time_utc.txt",
            failure_signal=signal,
            verifier="server",
            is_deterministic=False
        )

    return None


def detect_extended_key_usage_constraint_case(out_dir: Path) -> Optional[Dict[str, Any]]:
    """
    Detects: UsageConstraintFailure > ExtendedKeyUsageConstraintCase
    Direction: server verifies client
    Deterministic: No (log-based)
    Evidence: server/error.log
    """
    archetype = "UsageConstraintFailure"
    case = "ExtendedKeyUsageConstraintCase"
    metadata = get_case_metadata(archetype, case)

    error_log = read_text(out_dir, metadata["evidence_file"])
    signal = first_regex_match(error_log, metadata["signals"])
    if not signal:
        return None

    return build_failure_result(
        archetype,
        case,
        evidence_file=metadata["evidence_file"],
        failure_signal=signal,
        verifier="server",
        is_deterministic=False
    )


def detect_basic_constraints_violation_case(out_dir: Path) -> Optional[Dict[str, Any]]:
    """
    Detects: UsageConstraintFailure > BasicConstraintsViolationCase
    Direction: server verifies client
    Deterministic: Yes (cert field inspection)
    Evidence: certs/fields/client_cert.txt
    """
    archetype = "UsageConstraintFailure"
    case = "BasicConstraintsViolationCase"
    metadata = get_case_metadata(archetype, case)

    fields = read_text(out_dir, metadata["evidence_file"])
    if not fields:
        return None

    has_basic_constraints = re.search(r"Basic Constraints", fields, flags=re.IGNORECASE)
    has_ca_true = re.search(r"CA:TRUE", fields, flags=re.IGNORECASE)

    if has_basic_constraints and has_ca_true:
        signal = "Basic Constraints indicates CA:TRUE on client credential"
        return build_failure_result(
            archetype,
            case,
            evidence_file=metadata["evidence_file"],
            failure_signal=signal,
            verifier="server",
            is_deterministic=True
        )

    return None


def detect_dns_san_mismatch_case(out_dir: Path) -> Optional[Dict[str, Any]]:
    """
    Detects: SubjectIdentityMismatchFailure > DnsSanMismatchCase
    Direction: client verifies server
    Deterministic: No (log-based)
    Evidence: client/handshake.txt
    """
    archetype = "SubjectIdentityMismatchFailure"
    case = "DnsSanMismatchCase"
    metadata = get_case_metadata(archetype, case)

    handshake = read_text(out_dir, metadata["evidence_file"])
    signal = first_regex_match(handshake, metadata["signals"])
    if not signal:
        return None

    return build_failure_result(
        archetype,
        case,
        evidence_file=metadata["evidence_file"],
        failure_signal=signal,
        verifier="client",
        is_deterministic=False
    )


# ===== BASELINE SUCCESS =====
def check_request_accepted(out_dir: Path) -> bool:
    """
    Check if the request actually reached Flask, regardless of verification failures.
    This is used to distinguish hard failures from soft-fail warnings.
    Evidence:
      - server/flask_container_logs_since_run.txt contains request handling lines.
    """
    flask_logs = read_text(out_dir, "server/flask_container_logs_since_run.txt")
    return bool(re.search(r'"(GET|POST|PUT|DELETE)\s+/', flask_logs, flags=re.IGNORECASE))


# ===== ANALYZER ORCHESTRATION =====
def analyze(out_dir: Path) -> Dict[str, Any]:
    """
    Analyzer follows the trust decision graph model (see docs/trust-decision-graph.md)

    The analyzer checks for verification failures first, then checks if the request
    was accepted despite the failure (soft-fail/warning) or rejected (hard failure).
    """
    detectors = [
        # Step 1 - Peer Certificate Presentation
        detect_missing_client_certificate_case,

        # Step 2 - Trust Anchor Resolution
        detect_untrusted_self_signed_leaf_case,
        detect_wrong_trust_anchor_server_cert_case,
        detect_wrong_trust_anchor_client_cert_case,

        # Step 3 - Path Building
        detect_missing_intermediate_server_cert_case,
        detect_missing_intermediate_client_cert_case,

        # Step 4 - Proof of Possession
        detect_certificateverify_signature_mismatch_case,

        # Step 5 - Time Validity
        detect_expired_server_cert_case,
        detect_expired_client_cert_case,
        detect_not_yet_valid_server_cert_case,
        detect_not_yet_valid_client_cert_case,

        # Step 6 - Usage Constraints
        detect_extended_key_usage_constraint_case,
        detect_basic_constraints_violation_case,

        # Step 7 — Identity Binding
        detect_dns_san_mismatch_case,
    ]

    # Check if request was accepted (reached Flask)
    request_accepted = check_request_accepted(out_dir)

    # Try to detect verification failures
    for detector in detectors:
        result = detector(out_dir)
        if result:
            # Verification failure detected but request was accepted: downgrade to soft-fail warning.
            if request_accepted:
                result["warning"] = True
                result["status"] = "ACCEPT"
                result["symptom"] = f"WARNING: {result['symptom']} However, request was accepted (soft-fail configuration)."
            return result

    # No verification failures detected: check if request succeeded
    if request_accepted:
        return build_success_result(
            evidence_file="server/flask_container_logs_since_run.txt",
            success_signal="Flask logs show request handling (request reached Flask).",
        )

    return build_unknown_result(out_dir)


# ===== OUTPUT FORMATTING =====
def format_result_text(result: Dict[str, Any]) -> str:
    """
    Render a readable terminal and text-file summary
    """
    status = result.get("status")
    warning = result.get("warning")

    if status == "ACCEPT" and warning:
        display_status = "WARNING (soft-fail: verification failed but request accepted)"
    elif status == "ACCEPT":
        display_status = "SUCCESS"
    else:
        display_status = "FAILURE"

    step_block = ""
    if result.get("decision_step"):
        step = result["decision_step"]
        step_block = (
            f"Step:          {step['step_id']} — {step['step_name']}\n"
            f"Decision:      {step['decision']}\n"
            f"Failing input: {result.get('failing_input', '')}\n"
        )


    return (
        "----------Run Analysis----------\n"
        f"Result:       {display_status}\n"
        f"Archetype:    {result.get('archetype', '')}\n"
        f"Case:         {result.get('case', '')}\n"
        f"{step_block}"
        f"Detected by:  {result.get('detected_by', '')}\n"
        "\n"
        "Evidence:\n"
        f"  file:   {result.get('evidence_file', '')}\n"
        f"  signal: {result.get('failure_signal', '')}\n"
        "\n"
        "Symptom:\n"
        f"  {result.get('symptom', '')}\n"
        "\n"
        "Minimal fix:\n"
        f"  {result.get('minimal_fix', '')}\n"
    )


def write_outputs(out_dir: Path, result: Dict[str, Any]) -> None:
    """
    Persist analysis outputs along with the evidence dir in:
      - result.json
      - result.txt
    """
    (out_dir / "result.json").write_text(json.dumps(result, indent=2))
    (out_dir / "result.txt").write_text(format_result_text(result))

# ===== MAIN =====
def main() -> int:
    """
    python3 scripts/analyze_run.py <OUT_DIR>
    """
    if len(sys.argv) != 2:
        print("ERROR: usage: python3 scripts/analyze_run.py <OUT_DIR>", file=sys.stderr)
        return 2

    out_dir = Path(sys.argv[1]).resolve()
    if not out_dir.exists():
        print(f"ERROR: OUT_DIR not found: {out_dir}", file=sys.stderr)
        return 2

    result = analyze(out_dir)
    write_outputs(out_dir, result)
    print(format_result_text(result).strip())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())